spring:
  application:
    name: points-service
  datasource:
    url: jdbc:postgresql://localhost:5432/le_points
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  grpc:
    server:
      port: 9090

