package org.loyaltyengine.points_service.modules.points.services;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.loyaltyengine.points.v1.model.ErrorType;
import org.loyaltyengine.points_service.common.exceptions.BadRequestException;
import org.loyaltyengine.points_service.common.exceptions.NotFoundException;
import org.loyaltyengine.points_service.modules.points.dtos.DebitPointsResultDto;
import org.loyaltyengine.points_service.modules.points.dtos.CreatePointDto;
import org.loyaltyengine.points_service.modules.points.dtos.PointDto;
import org.loyaltyengine.points_service.modules.points.dtos.PointsResultDto;
import org.loyaltyengine.points_service.modules.points.enums.PointStatus;
import org.loyaltyengine.points_service.modules.points.mappers.PointMapper;
import org.loyaltyengine.points_service.modules.points.models.Point;
import org.loyaltyengine.points_service.modules.points.repositories.PointRepository;
import org.loyaltyengine.points_service.modules.transactions.dtos.CreatePointTransactionDto;
import org.loyaltyengine.points_service.modules.transactions.services.PointTransactionService;
import org.loyaltyengine.points_service.modules.types.dtos.PointTypeDto;
import org.loyaltyengine.points_service.modules.types.services.PointTypeService;
import org.loyaltyengine.points_service.shared.dtos.PageDto;
import org.loyaltyengine.points_service.shared.dtos.PaginationQueryDto;
import org.loyaltyengine.points_service.shared.enums.TransactionReason;
import org.loyaltyengine.points_service.shared.enums.TransactionType;
import org.loyaltyengine.points_service.shared.utils.SharedUtils;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.OffsetDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class PointServiceImpl implements PointService {
    private static final String DEFAULT_POINT_TYPE_ID = "pt_general";

    private final PointRepository repository;
    private final PointMapper mapper;
    private final PointTypeService pointTypeService;
    private final PointTransactionService pointTransactionService;

    @Override
    public PointDto grantPoints(CreatePointDto dto) {
        log.info("Creating new  for propertyId: {}, customerId: {}", dto.getPropertyId(), dto.getCustomerId());
        // Grant points by type if provided
        Integer numberOfPoints;
        if (dto.getPointTypeId() != null) {
            PointTypeDto pointType = pointTypeService.getPointType(dto.getPropertyId(), dto.getPointTypeId());
            numberOfPoints = pointType.getNumberOfPoints();
        } else {
            numberOfPoints = dto.getNumberOfPoints();
            if (numberOfPoints == null) {
                throw new BadRequestException(ErrorType.INVALID_REQUEST, "Number of points is required",
                        "Either number of points or point type id must be provided");
            }
        }

        // Build the new point
        Point newPoint = Point.builder()
                .numberOfPoints(numberOfPoints)
                .remainingPoints(numberOfPoints)
                .propertyId(dto.getPropertyId())
                .customerId(dto.getCustomerId())
                .description(dto.getDescription())
                .expireAt(dto.getExpireAt())
                .status(PointStatus.ACTIVE)
                // Set default values if not provided
                // Although some values will be generated by the OpenAPI schemas, just in case
                .validFrom(dto.getValidFrom() != null ? dto.getValidFrom() : OffsetDateTime.now())
                .pointTypeId(dto.getPointTypeId() != null ? dto.getPointTypeId() : DEFAULT_POINT_TYPE_ID)
                .exchangeable(dto.getExchangeable() != null ? dto.getExchangeable() : Boolean.TRUE)
                .build();

        // Save the new point
        Point savedPoint = repository.save(newPoint);

        // Create transaction
        pointTransactionService.createPointTransaction(CreatePointTransactionDto.builder()
                .pointId(savedPoint.getPointId())
                .propertyId(dto.getPropertyId())
                .customerId(dto.getCustomerId())
                .amount(savedPoint.getNumberOfPoints())
                .type(TransactionType.CREDIT)
                .reason(TransactionReason.GRANT)
                .build()
        );

        // Map to dto
        return mapper.toDto(savedPoint);
    }

    @Override
    public PointsResultDto getCustomerPoints(String propertyId, String customerId, PaginationQueryDto paginationQueryDto) {
        log.info("Getting points for propertyId: {}, customerId: {}", propertyId, customerId);
        // Create pageable
        Pageable pageable = SharedUtils.buildValidPageable(paginationQueryDto);

        // Get points
        Page<Point> points = repository.findByPropertyIdAndCustomerId(propertyId, customerId, pageable);

        // Map to dto
        return PointsResultDto.builder()
                .page(PageDto.builder()
                        .page(paginationQueryDto.getPage())
                        .size(paginationQueryDto.getSize())
                        .totalPages(points.getTotalPages())
                        .totalElements(points.getTotalElements())
                        .build())
                .points(mapper.toDto(points.getContent()))
                .build();
    }

    @Override
    public PointDto getPoint(String propertyId, String customerId, String pointId) {
        Point point = repository.findByPointIdAndPropertyIdAndCustomerId(pointId, propertyId, customerId)
                .orElseThrow(() -> new NotFoundException(ErrorType.NOT_FOUND, "Point not found", "Point not found"));

        return mapper.toDto(point);
    }

    @Override
    public DebitPointsResultDto debitPoints(String propertyId, String customerId, Integer pointsToDebit) {
        log.info("Debiting {} points for propertyId: {}, customerId: {}", pointsToDebit, propertyId, customerId);
        OffsetDateTime now = OffsetDateTime.now();
        // Get points
        List<Point> points = repository
                .findActiveOldestByPropertyIdAndCustomerId(propertyId, customerId, now);

        // Determine total remaining points
        int totalRemaining = points.stream()
                .mapToInt(Point::getRemainingPoints)
                .sum();

        if (totalRemaining < pointsToDebit) {
            throw new BadRequestException(ErrorType.INSUFFICIENT_POINTS, "Not enough points",
                    "Customer id: " + customerId + " has not enough points");
        }

        // Deduct points
        int pointsToDeduct = pointsToDebit;
        for (Point point : points) {
            if (pointsToDeduct <= 0) {
                break;
            }

            int remainingPoints = point.getRemainingPoints();
            int toDeduct = Math.min(remainingPoints, pointsToDeduct);
            // Update and save point
            point.setRemainingPoints(remainingPoints - toDeduct);
            repository.save(point);

            // Create transaction
            pointTransactionService.createPointTransaction(CreatePointTransactionDto.builder()
                    .pointId(point.getPointId())
                    .propertyId(point.getPropertyId())
                    .customerId(point.getCustomerId())
                    .amount(toDeduct)
                    .type(TransactionType.DEBIT)
                    .reason(TransactionReason.REDEMPTION)
                    .build());

            pointsToDeduct -= toDeduct;
        }

        return DebitPointsResultDto.builder()
                .totalRemainingPoints(totalRemaining - pointsToDebit)
                .totalDebited(pointsToDebit)
                .build();
    }
}
